### ISSUE TITLE
Foundry not installing dependency automatically.

### ISSUE THREAD

**Issue by Fio-Fio-Fio** [Z3nner/lancer-weapon-fx#17]
When I went to install the v10 version of Lancer Weapon FXs, Foundry spat out an error when attempting to grab the manifest for Spell Effects Cartoon, manually grabbing that module fixed the problem.

**Comment by dodgepong** [comment]
Huh, I copied the manifest link from Foundry's site. I'll verify it again.

**Comment by MaxPelly** [comment]
For me it didn't grab the jb2a module, had to install it manually

**Comment by Z3nner** [comment]
> For me it didn't grab the jb2a module, had to install it manually

That's working as intended unfortunately.

There is a free and paid version of JB2A and they're entirely separate modules so we can't require one or the other.
Instead the module runs a check for o ensure o e or the other is installed and kicks back an error only if it detects neither.

**Comment by MaxPelly** [comment]
aah, guess i missed the error then, first I saw was a pile of file not found errors

**Comment by Z3nner** [comment]
Dodgepong, I'm wondering if you could take a look at the code Gazkhan added awhile back to handle the JB2A module pair problem.  Lines 37-43 in weaponfx.js
From what I've gathered from a few folks on Pilot.NET, the error message either isn't showing up or doesn't last long enough to be effective.  Is there a way to make it stick around longer, or not generate until several seconds later than it currently does?

For others curious, my game plan for the future is to eventually remove any animations that are from Spell effects or Spell Effects cartoon and just stick with whats offered by JB2A.  JB2A has animations that will easily replace the few animations I used from Spell Effects.

**Comment by dodgepong** [comment]
It does show a message on load, but it's pretty quick. Not sure a better way to handle it, honestly. Seems like that's what Automated Animations does too.
