### ISSUE TITLE
The automatic FX aren't working?

### ISSUE THREAD

**Issue by nsurette** [Z3nner/lancer-weapon-fx#19]
I might be really dumb but here goes.
Foundry 10.291
Lancer 1.4.2
Lancer Weapon Effects 1.6.1 + dependencies.

The main page says it should just work.
I have targeted an anime with the bullseye target function. Switched to the select unit button, selected the mech (the unit border changes colours thanks to hex token support module), opened the mech page, attack the enemy with a Cyclone Superheavy pulse rifle and an assault rifle and gotten no effects.

The compendium exists in the compendium folder. So I'm not sure if I'm missing something or not. The front page says it should just work.

**Comment by dodgepong** [comment]
If you hit F12, are there any errors in the console?

**Comment by nsurette** [comment]
Okay. So First Sequencer said it needed SocketLib (I don't know why it's not a required dependency) so I enabled that and now I'm getting actual errors.


![image](https://user-images.githubusercontent.com/7799011/213936882-7d0033a2-efc1-430f-94e5-e66870f64cc6.png)

**Comment by Z3nner** [comment]
Do you have either the free or premium version of JB2A installed?

**Comment by nsurette** [comment]
The free version that installs off the foundry package page.

**Comment by dodgepong** [comment]
I don't see JB2A listed in your module list in the screenshot, which means it's not installed.

**Comment by nsurette** [comment]
I have no idea how that happened -_- and now I feel so dumb for wasting your time. I activated the JB2A module and now it works. Sigh.

Thank you for the help and sorry for wasting your time on my brainfart.

**Comment by Z3nner** [comment]
No worries, glad you got it working. Enjoy.
