### ISSUE TITLE
Updated requirements?

### ISSUE THREAD

**Issue by Kingrames** [Z3nner/lancer-weapon-fx#51]
I just performed an "update all" for my foundry modules, and this module told me that it had a new requirement: jb2a-patreon, which is not available for download. Is this an error?

**Comment by cirrahn** [comment]
It is an "optional" requirement. The free version also works: https://foundryvtt.com/packages/JB2A_DnD5e

**Comment by Kingrames** [comment]
I should clarify: the update process was interrupted with an error message that prompted me to try and download the file but the button to download it was greyed out, this has never happened before when updating modules.

**Comment by Z3nner** [comment]
Kingrames, we are well aware of the message you received, it is a stock message delivered whenever someone who doesn't have a recommended module installed.
JB2A has a free and paid version, you need one or the other for LwFX.  We cannot make them both required, but this method ensures users always have one or the other, and is in response to a long series of issues with people trying to run the module without JB2A's assets.

Please, in the future, read any error messages carefully.  In this case, you would have seen that it clearly stated that JB2A patreon was not required, but may enrich your experience, or something to that effect.
You state that the update was interrupted, what version is currently showing as active on your Foundry?

**Comment by Kingrames** [comment]
My version is 2.0.1, and for clarity, I also have the free version of JB2A installed. 

The issue appears to be non-reproducible however. Sorry for the confusion. I suppose you can close this.
