### ISSUE TITLE
Suggestion: Automatically map the different macros to the relevant weaponds/loadouts on LCP file import

### ISSUE THREAD

**Issue by OmnesPotens** [Z3nner/lancer-weapon-fx#6]
The title essentially summarizes the ask. Alternatively, maybe map simply based on name.

**Comment by dodgepong** [comment]
I believe this is resolved, at least as far as official manually-mapped weapons go. Future improvements include:

* Expanding supported weapons to Dustgrave and SSMR
* Adding a heuristic to make a guess as to what sort of effect to give homebrew weapons
* Allowing users to change what animations are assigned to what weapons
